version: '3.5'
services:
 backend:
  build: .
  command: ["./runbackend"]
  ports:
   - "8081:8081"
  environment:
   - PORT=8081
   - FLASK_APP=project
   - FLASK_DEBUG=true
   - rabbitmq_ampq=pyamqp://guest@rabbitmq//
   - redis_backend=redis://redis
  depends_on:
   - celery
   - postgres
   - rabbitmq
   - redis

 celery:
  build: .
  command: ["./celery"]
  ports:
   - "5001:5001"
  environment:
   - PORT=8081
   - FLASK_APP=project
   - FLASK_DEBUG=true
   - rabbitmq_ampq=pyamqp://guest@rabbitmq//
   - redis_backend=redis://redis
  depends_on:
   - postgres
   - rabbitmq
   - redis

 rabbitmq:
  image: "rabbitmq:3-management"
  hostname: "rabbit"
  ports:
   - "15672:15672"
   - "5672:5672"
  labels:
   NAME: "rabbitmq"


 redis:
  image: redis
  container_name: redis
  ports:
    - "6379:6379"
  expose:
    - 6379

 postgres:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
        - POSTGRES_USER=user
        - POSTGRES_PASSWORD=password
        - POSTGRES_DB=mydb
